tunnel: blog
credentials-file: /root/.cloudflared/4721012c-0f3a-483d-af59-303372797358.json   #<Tunnel-UUID>修改为自己的
protocol: http2
ingress:
  - hostname: wzmzero.top #自定义的域名
    service: http://localhost:85   #需要代理服务的端口
  - hostname: www.wzmzero.top #自定义的域名
    service: http://localhost:85   #需要代理服务的端口
  - hostname: bt.wzmzero.top #自定义的域名
    service: http://localhost:8090   #需要代理服务的端口  
  - service: http_status:404

